"""empty message

Revision ID: e3038eabfc12
Revises: f1dc7958582a
Create Date: 2024-04-23 20:02:51.324848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3038eabfc12'
down_revision = 'f1dc7958582a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])
        batch_op.drop_column('item_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_status', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
